---
apiVersion: v1
kind: Service
metadata:
  name: reconciliation-service
spec:
  selector:
    app: reconciliation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer